# Generated by Django 4.2.1 on 2023-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
